### PR TITLE
Use full-text column for full-text search.

### PR DESCRIPTION
**Pull request by jmcarp**
Fixes a typo on typeahead search resources and adds a regression test.

### CODE REVIEW

**Comment by noahmanger** [comment]
Should this be included in the release?

**Comment by ccostino** [comment]
I can easily merge if it should be, this was one of the next PRs on my list to review before being out yesterday and dealing with staging deploys.

@jmcarp, was it your intention to get this in with the next release or should this wait until after?

**Comment by ccostino** [comment]
Per our Slack conversation, we'll merge this into our a release branch directly for now and bring it into `develop` a bit later.

**Comment by ccostino** [comment]
Closing this as is since we'll merge the release branch back into `develop`.

**Pull request closed without merging**
