### PR TITLE
Because Python 3

### PR DESCRIPTION
**Pull request by arowla**
Don't merge until you're ready to lose the old totals endpoints.
27 additions and 1,132 deletions.

:microphone: :arrow_down:

### CODE REVIEW

**Comment by cmc333333** [comment]
Whoo whoo!

**Comment by arowla** [comment]
Spoke too soon... Got a few things to clean up. So yeah. Hold that merge.

**Comment by cmc333333** [comment]
Also, don't merge until you're ready to lose your _mind_
:dance_party:

**Comment by arowla** [comment]
Oh yes, this will definitely call for a robot dance party or ten.

**Comment by arowla** [comment]
Speaking of robots... where is Travis?

**Comment by rjmajma** [comment]
That is a good question.

**Comment by LindsayYoung** [comment]
The totals front-end refactor is issue #399 

(Just wanted to link that so we don't have to look it up later.)

**Comment by LindsayYoung** [comment]
I was looking into why Travis is MIA. By referencing the requests on the OpenFEC blogs https://travis-ci.org/18F/openFEC/requests It says, missing commit for recent missing builds. Other people with this issue fixed it by editing the tags as outlined here- https://github.com/travis-ci/travis-ci/issues/2495

**Comment by arowla** [comment]
I just merged master into my branch and pushed it. There were some conflicts, including a conflict on a deleted file (changed in master, deleted in this branch). Maybe it was bad enough to make Travis go MIA. Anyway, he appears to be back. :confetti_ball:

**Pull request merged**
