### PR TITLE
Remove unused command

### PR DESCRIPTION
**Pull request by vrajmohan**

### CODE REVIEW

**Comment by ccostino** [comment]
Ah good catch, @vrajmohan!  It looks like a test might need to be updated though, or at least investigated?  One of the Travis builds failed:  https://travis-ci.org/18F/openFEC/builds/273149717#L1341

**Comment by ccostino** [comment]
Also, it looks like we should remove the `refresh_itemized` command from there and from `manage.py` as well (and its underlying methods) - that still got called during the nightly updates and failed:

```
Traceback (most recent call last):
  File "/home/vcap/app/webservices/tasks/refresh.py", line 20, in refresh
    manage.refresh_itemized()
AttributeError: module 'manage' has no attribute 'refresh_itemized'
```

That whole set of methods refers to the code that used to exist in the Python partition code, which is no longer there.

**Comment by ccostino** [comment]
FYI that the Travis error seems to be breaking other PR tests now, too.

**Comment by LindsayYoung** [comment]
Thank you both for getting this done!

**Pull request merged**
