### PR TITLE
New tests for sorting

### PR DESCRIPTION
**Pull request by jontours**
Currently added a new tests in test_utils to test hiding nulls for candidate totals.  This is to ensure that any changes to this endpoint doesn't not cause any regressions.

Still need to add a test for Elections, unfortunately I don't know of any easier ways of doing this, but it does work.

### CODE REVIEW

**Comment by jontours** [comment]
This is good to go.  There may be some more tests to write but these two seem to be great edge cases.  Currently tests Election totals and candidate totals endpoint.

**Comment by jontours** [comment]
Closes https://github.com/18F/openFEC/issues/1823

**Comment by LindsayYoung** [comment]
Thank you!

**Comment by jontours** [comment]
Thanks for taking a look, it turned out to be quite a challenge to write these two tests.  But, I learned a good deal about the election endpoint in the process.

**Pull request merged**
