### PR TITLE
Schedule F (party coordinated expenditures)

### PR DESCRIPTION
**Pull request by jontours**
Most functionality good to go.

### CODE REVIEW

**Comment by jontours** [comment]
Ready to go just needs swagger-ui documentation.

**Comment by jontours** [comment]
@LindsayYoung @ccostino This PR is ready to merge.  I made the same changes to this endpoint that were made to schedule C, so everything should be set. However, trust but verify.  I've checked out the filters and sorting and think they are ready, but may have missed one.  I'll give it look one more time.

**Comment by LindsayYoung** [comment]
This works great. Thanks again!

**Comment by noahmanger** [comment]
Just noticed something weird: if there's a trailing slash at the end like: `/v1/schedules/schedule_f/` it throws a 404. Any idea what's up?

**Comment by noahmanger** [comment]
Same thing with `schedule_c`. The other endpoints seem to support it fine, so we should be consistent

**Comment by LindsayYoung** [comment]
just needs a trailing slash in the urls

**Comment by jontours** [comment]
Oops.  I can open PRs off of the release branch to fix this.

**Comment by noahmanger** [comment]
@jontours we fixed it already!

**Comment by jontours** [comment]
Noticed!  Thanks for getting to it!

**Pull request merged**
