### PR TITLE
Restore API key to docs in production.

### PR DESCRIPTION
**Pull request by jmcarp**
h/t @lindsayyoung

### CODE REVIEW

**Comment by LindsayYoung** [comment]
Thanks!

**Comment by LindsayYoung** [comment]
I am getting an error locally

```
Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    from webservices.rest import app, db
  File "/Users/lindsayyoung/projects/openFEC/webservices/rest.py", line 23, in <module>
    from webservices import args
  File "/Users/lindsayyoung/projects/openFEC/webservices/args.py", line 14, in <module>
    from webservices.common.models import db
  File "/Users/lindsayyoung/projects/openFEC/webservices/common/models/__init__.py", line 5, in <module>
    from .aggregates import *  # noqa
  File "/Users/lindsayyoung/projects/openFEC/webservices/common/models/aggregates.py", line 1, in <module>
    from webservices import utils
  File "/Users/lindsayyoung/projects/openFEC/webservices/utils.py", line 33, in <module>
    Resource = use_kwargs({'api_key': API_KEY_ARG})(Resource)
  File "/Users/lindsayyoung/.virtualenvs/newfec/lib/python3.4/site-packages/flask_smore/__init__.py", line 85, in wrapper
    func.__dict__.setdefault('__args__', []).insert(0, {
AttributeError: 'mappingproxy' object has no attribute 'setdefault'
```

**Comment by jmcarp** [comment]
Tests are passing on Travis. Try upgrading requirements:
```
pip install -U git+https://github.com/jmcarp/flask-smore@master
pip install -U git+https://github.com/marshmallow-code/smore@dev
```

**Comment by LindsayYoung** [comment]
That was it, thanks.

**Pull request merged**
