### PR TITLE
Added coverage dates to totals endpoint

### PR DESCRIPTION
**Pull request by arowla**
This will add the earliest coverage date as `coverage_start_date` and the latest as `coverage_end_date`.

### CODE REVIEW

**Comment by arowla** [comment]
For #317.

**Comment by LindsayYoung** [comment]
I <3 Coverage dates!

**Comment by rjmajma** [comment]
Space/Time achievement unlocked!

**Comment by arowla** [comment]
:clock11: :rocket: :clock10:

**Comment by arowla** [comment]
@rjmajma wins

**Comment by rjmajma** [comment]
No, @arowla. We all win.

**Pull request merged**
