### PR TITLE
Implement multiple sort for filings

### PR DESCRIPTION
**Pull request by jontours**
As it turned out grouping committee filings was fairly easy, just have to tie in multiple sort options.

### CODE REVIEW

**Comment by noahmanger** [comment]
Excellent. Let's connect on this on Tuesday to compare with how the designs are shaping up.

**Comment by jontours** [comment]
After taking a look at the design work and the invision example, this http request is close: ```http://localhost:5000/v1/filings/?sort=-coverage_end_date&sort=report_type_full&sort=-beginning_image_number&per_page=100&committee_id=C00326801&page=2```.  However filtering down to the separate categories may be tricky (e.g. misc, 24/48, statement of org., etc) but I think is feasible with the filters we already have.

**Comment by jontours** [comment]
This is ready to go and ready for review; after @noahmanger gives it a thumbs up.  But multiple sort is functioning and was a rather lightweight change at the end of the day.  This request is a sample request to see "regular" filings from Tammy Baldwin's committee: 
```
http://localhost:5000/v1/filings/?sort=-coverage_end_date&sort=report_type_full&sort=-beginning_image_number&per_page=100&committee_id=C00326801&page=1&form_type=F3&form_type=F3L&form_type=RFAI
```

**Comment by LindsayYoung** [comment]
Works for me locally. Though, maybe we should add a test, since we have had a lot of issues with sorting

**Comment by jontours** [comment]
I can see if I can get something for that before the release.  But may have to be moved to build off the release branch if it proves tricky (shouldn't be).

**Comment by LindsayYoung** [comment]
I am merging this and @jontours will make the test as a separate PR

https://github.com/18F/openFEC/issues/2207

**Pull request merged**
