### PR TITLE
Add full election flag to committee history view.

### PR DESCRIPTION
**Pull request by jmcarp**
Add an `election_full` flag to the committee history view. When passed,
find all committees associated with the given candidate for the given
election.

[Resolves https://github.com/18F/openFEC-web-app/issues/998]

### CODE REVIEW

**Comment by noahmanger** [comment]
So I'm reading https://github.com/18F/openFEC-web-app/issues/998 as asking for both committees to be visible on the "full cycle" option. I see the correct committees showing for each sub-period, but only the most recent one is visible on full cycle.

**Comment by noahmanger** [comment]
Ah I wasn't running the right app branch. This is working well. I have one UI note though but will add it to that repo.

**Comment by LindsayYoung** [comment]
This looks good to me

**Comment by jmcarp** [comment]
Conflicts resolved @LindsayYoung

**Pull request merged**
