### PR TITLE
Added document_description and pdf_url to all efile reports summaries

### PR DESCRIPTION
**Pull request by jontours**
@noahmanger @ccostino @LindsayYoung, this PR adds the missing fields needed to the efiling summaries: document_description and pdf_url.  Verified that the urls exist, also fixed an ambiguous column name: qual -> qualified_muliticandidate_committee.  Gleaned that from the linked form!!  Yay information!

### CODE REVIEW

**Comment by jontours** [comment]
Issue here: https://github.com/18F/openFEC/issues/1905

**Comment by noahmanger** [comment]
Works great for efilings. My bad for not catching this earlier, but apparently we need `document_description` for the regular reports endpoints as well (they have `report_type_full` but not `document_description`. Is that trivial to add?

**Comment by jontours** [comment]
I'd say it is trivial to add.  I can add it to this PR.

**Comment by jontours** [comment]
Ok, this should be ready now that `document_description` is added to processed reports.

**Pull request merged**
