### PR TITLE
Feature/use views staging prod

### PR DESCRIPTION
**Pull request by LindsayYoung**
This is for using views in staging and production.

Just got schemas to build staging, need to: 

- [x] refactor test data
- [x] run update_sched e
- [x] make sure nightly process runs

### CODE REVIEW

**Comment by LindsayYoung** [comment]
Still working on  getting the updates to work on staging

**Comment by jontours** [comment]
doh, seems like there are some unrelated commits here.

**Comment by LindsayYoung** [comment]
The commits are because I forked my view branch and merged in the release. 

I also changed it to target the release.

I will start renaming things in the test data tomorrow. I will still need some help with getting the tests to pass with the schema changes. If tomorrow, you could help me with that @jontours it would be really appreciated.

thanks

**Comment by LindsayYoung** [comment]
update for test data so far:
```
create schema fecapp;

create table  fecapp.cal_category as (select * from cal_category);
drop table cal_category;
create table  fecapp.cal_category_subcat as (select * from cal_category_subcat);
drop table cal_category_subcat;
create table  fecapp.cal_event as (select * from cal_event);
drop table cal_event;
create table  fecapp.cal_event_category as (select * from cal_event_category);
drop table cal_event_category;
create table  fecapp.cal_event_status as (select * from cal_event_status);
drop table cal_event_status;
create table  fecapp.trc_election as (select * from trc_election);
drop table trc_election;
create table  fecapp.trc_election_dates as (select * from trc_election_dates);
drop table trc_election_dates;
create table  fecapp.trc_report_due_date as (select * from trc_report_due_date);
drop table trc_report_due_date;

create table disclosure.cand_inactive as (select * from cand_inactive);

alter table fec_vsum_sched_e rename to fec_vsum_sched_e_base;
alter table fec_vsum_sched_e_base drop column pg_date;
create view fec_vsum_sched_e_vw as (select * from fec_vsum_sched_e_base);

alter table fec_vsum_f57 drop column pg_date;
create view fec_vsum_f57_vw as (select * from fec_vsum_f57);

create view fec_vsum_f5_vw as (select * from fec_vsum_f5);

create view fec_vsum_f3_vw as (select * from fec_vsum_f3);
create view fec_vsum_f3p_vw as (select * from fec_vsum_f3p);
create view fec_vsum_f3x_vw as (select * from fec_vsum_f3x);
create view fec_vsum_f76_vw as (select * from fec_vsum_f76);

alter table fec_vsum_sched_e rename to fec_vsum_sched_e_base;
alter table fec_vsum_sched_e_base drop column pg_date;
create view fec_vsum_sched_e_vw as (select * from fec_vsum_sched_e_base);

create view fec_vsum_f1_vw as (select * from fec_vsum_f1);
create view fec_vsum_sched_f_vw as (select * from fec_vsum_sched_f);
create view fec_vsum_sched_c_vw as (select * from fec_vsum_sched_c);

create schema staging;
create table staging.ref_rpt_tp as (select * from ref_rpt_tp);
drop table ref_rpt_tp;
```

**Comment by jontours** [comment]
huge +1 on that commit comment, haha

**Comment by LindsayYoung** [comment]
I reviewed your commits and election and report dates were working with staging data. So I agree it is good to go!

**Pull request merged**
