### PR TITLE
First pass on efiling filings!

### PR DESCRIPTION
**Pull request by LindsayYoung**
It runs!

Still have some todos, documentation to write and tests. Also, the data is only on dev and production.

### CODE REVIEW

**Comment by LindsayYoung** [comment]
needs test data

**Comment by noahmanger** [comment]
Curious from @ccostino and @jontours if this seems like something we'd be able to get reviewed and merged in for this release? If so, I can look to prioritize the related frontend work.

**Comment by jontours** [comment]
I can give it a review as the work will somewhat mirror the work I'm doing on the summary efiling.

**Comment by noahmanger** [comment]
Related note from @PaulClark2 in Slack re: the "A" and "N" that appears in the "form_type": 

"A" means it is an amendment, i.e. `F3A` is a form 3 amendment. Also: 

> Another way to determine if a filing is an amendment is from the `reps` table. `Rptnum` = 0 is new `repnum` not equal to 0 is amendment.

**Comment by LindsayYoung** [comment]
I am going to point this at the release branch

**Pull request closed without merging**
