### PR TITLE
adding feature space manifest

### PR DESCRIPTION
**Pull request by anthonygarvan**
This adds the manifest for the new `feature` space. I have already deployed this on the space, so I know it works :).

### CODE REVIEW

**Comment by ccostino** [comment]
Thanks, @anthonygarvan!  We might also want to consider adding support in the `./tasks.py` file used by `invoke`.  Perhaps we could tie it to branches that start with `feature` just like branches that start with `release` are tied to staging.  Any thoughts on this?

/cc @LindsayYoung and @adborden

**Comment by LindsayYoung** [comment]
I like the idea of the feature space being purposefully deployed so it doesn't get clobbered if we are using it for demos or testing.

**Comment by anthonygarvan** [comment]
Yeah I agree with @LindsayYoung, feature should not be automatically deployed.

**Comment by ccostino** [comment]
Ah good point, and this gives us the ability to retain auto-deploys on dev so that it stays updated with everything merged to-date.  Merging!

**Pull request merged**
