### PR TITLE
Feature/test swagger

### PR DESCRIPTION
**Pull request by jmcarp**
This patch adds an integration test verifying that the Swagger output is correct, and fixes a number of Swagger errors that we hadn't noticed before.

### CODE REVIEW

**Comment by arowla** [comment]
Looks like there are some more Swagger errors, according to the Travis build? Do you want to fix them as part of this or go ahead an merge? LGTM otherwise.

**Comment by jmcarp** [comment]
Yep, fixing now.

**Comment by jmcarp** [comment]
Build passing :joy_cat:

**Comment by arowla** [comment]
um... how?

**Comment by jmcarp** [comment]
I pushed some fixes to my fork of smore.

**Comment by arowla** [comment]
:+1:

**Pull request merged**
