### PR TITLE
Feature/revert calendar

### PR DESCRIPTION
**Pull request by LindsayYoung**
This will shift the source of the calendar endpoint to the he three fecapp.cal_event tables (known as the old calendar) This will give people a more consistent data entry experience and give FEC more control over the display of events.

- This can be a view now, so additions and changes should show up more quickly
- We lost the state filter because the data does not support it

The work is done but this requires filter changes on the front end so don't merge it until that is ready.

### CODE REVIEW

**Comment by LindsayYoung** [comment]
Date filter works but some of the other fields are not working yet

**Comment by fec-jli** [comment]
We have pull to local and run api 
"state" filters are no longer exist in /calendar-dates/ and  /calendar-dates/export/

**Comment by LindsayYoung** [comment]
Got everything working- there is a change where we do need use calendar_category_id for category filtering, but it works pretty similarly 

Ready for you to look it over and merge Monday @fec-jli 

Thanks!

**Comment by LindsayYoung** [comment]
@vrajmohan or @ccostino wanted to see if this needed to be refactored to work with the new migration work

**Comment by ccostino** [comment]
@LindsayYoung yes, given the SQL changes.  We'll have to write a new migration to account for the changes at this point, right @vrajmohan?

**Comment by vrajmohan** [comment]
Yes, it would need to be written as a migration.

**Comment by LindsayYoung** [comment]
thanks for the flow catch- I thought I had gotten rid of the flow reference!

**Pull request merged**
