### PR TITLE
adding info & link about FEC data use restrictions

### PR DESCRIPTION
**Pull request by leahbannon**
cc @emileighoutlaw @konklone

### CODE REVIEW

**Comment by konklone** [comment]
I personally think this belongs in the README and the published API documentation, but not the LICENSE, since the LICENSE describes how people can use the software and not the data.

**Comment by leahbannon** [comment]
@konklone It will be in the API docs and I'm up for adding it to the README as well. 

This should also be in the license file. Users should be warned about this, in part because the license says "this project" not "the code in this repo only," but also because I think it's helpful to provide a heads up in the place that users expect to find restrictions on use.

**Comment by konklone** [comment]
> This should also be in the license file. Users should be warned about this, in part because the license says "this project" not "the code in this repo only," but also because I think it's helpful to provide a heads up in the place that users expect to find restrictions on use.

I don't agree -- I think putting data restriction information intermingled in the software license file could give users of the software the mistaken impression that the use restrictions on data apply to the software as well, which is not the case. People are free to fork the openFEC codebase and use it, or pieces of it, to (somehow) solicit donations or do things that are otherwise not allowed with the FEC's campaign finance data.

As a user of open data, I wouldn't expect the software license to address these issues. I would expect them to be addressed where the data is published and/or documented. Adding it to this project's README is even a bit superfluous, but on balance could work as a courtesy and extra layer of diligence, as it's more clearly detached from software licensing information.

**Comment by leahbannon** [comment]
Those are reasonable points, but the language in the license that says "this project" is ambiguous and the language in my pull request is clear that it applies to "the data."

**Comment by konklone** [comment]
That could well be worth a pull request to [our default LICENSE file](https://github.com/18F/open-source-policy/blob/master/LICENSE.md) if you think that "this project" is ambiguous phrasing for that file's purpose.

**Comment by LindsayYoung** [comment]
How about we add it here for now and think of a better solution later. I think it would be nice to have that as a separate file.

**Pull request merged**
