### PR TITLE
Fix transaction id in schedules and sort bug fixes

### PR DESCRIPTION
**Pull request by LindsayYoung**
The sort errors are fixed by adding a default sort order

For the transaction id, we had it going twice and the transaction_id was always null. Now we just have the string version going.

### CODE REVIEW

**Comment by LindsayYoung** [comment]
Also the transaction ids look odd to me, they are not similar if you look at different committees but they come from `tran_id`- so I think they are right.

**Comment by jontours** [comment]
@LindsayYoung I'll take a look at this, looks like an integration test is failing.

**Comment by jontours** [comment]
Seems the problem with the test is failing is that by adding a default sort order for `sched_b` of `disbursement_date` causes the ordering of the JSON entries to be reversed, which is kind of funny since the values are null for that.  There are probably lots of ways to fix it, maybe initialize the dates in the factory to enforce the ordering?

**Comment by LindsayYoung** [comment]
Thanks, adding dates to the factory makes sense to me. I'll do that now

**Comment by LindsayYoung** [comment]
the test I am seeing fail is memoed_subtotal which we don't filter by

**Pull request merged**
