### PR TITLE
[USE GITFLOW]Hotfix/sorting error

### PR DESCRIPTION
**Pull request by LindsayYoung**
adds default sort

### CODE REVIEW

**Comment by ccostino** [comment]
@LindsayYoung, should this go against `master` instead and be merged via `git-flow`?

**Comment by LindsayYoung** [comment]
Yes, use git flow. Good catch

**Comment by LindsayYoung** [comment]
updated!

**Comment by ccostino** [comment]
Thanks, @LindsayYoung!

**Pull request merged**
