### PR TITLE
Adding fields that were missing from reports and totals

### PR DESCRIPTION
**Pull request by LindsayYoung**
Making sure we have everything

### CODE REVIEW

**Comment by arowla** [comment]
Should this still be WIP?

**Comment by LindsayYoung** [comment]
Planning on finishing presidential tomorrow and giving it a once over

**Comment by LindsayYoung** [comment]
I added missing fields and did some modest name standardization. The tests aren't passing but I think things might be missing from the sample data.

**Comment by LindsayYoung** [comment]
No, the tests are really failing. Looking at that now.

**Comment by jmcarp** [comment]
LGTM :+1:

**Pull request merged**
