### PR TITLE
Hotfix/date sort bug

### PR DESCRIPTION
**Pull request by LindsayYoung**
The validation on the reporting and election endpoints is not working, I think we should take that validation down as a quick fix, but I would still like to understand why it suddenly had trouble validating these endpoints.

### CODE REVIEW

**Comment by LindsayYoung** [comment]
OK, I think it is not validating because there is not an index on due date. I will look at that now.

**Comment by LindsayYoung** [comment]
We don't create indexes on those, and I don't think we need to there is not that much data there.

**Comment by jmcarp** [comment]
@LindsayYoung, could you resolve the merge conflict? Hotfix PRs should normally target master, but since this change is so small, it's not worth retargeting.

**Comment by noahmanger** [comment]
Is this still relevant and needed?

**Comment by noahmanger** [comment]
Checking on this again. Still needed or should we close?

**Comment by LindsayYoung** [comment]
Let's kill it.

**Pull request closed without merging**
