### PR TITLE
FRQ Feature

### PR DESCRIPTION
**Pull request by jontours**
FRQ filers are included with results any time RFAI is passed as a filter.

### CODE REVIEW

**Comment by noahmanger** [comment]
Nice. The other piece of this is that FRQ document descriptions should also be prefaced with "RFAI".

**Comment by jontours** [comment]
Sweet, I'll add that.

**Comment by jontours** [comment]
"RFAI: " now prepended to FRQs.

**Comment by LindsayYoung** [comment]
taking a look now

**Comment by LindsayYoung** [comment]
Thank you!

**Pull request merged**
