### PR TITLE
feature/map nulls

### PR DESCRIPTION
**Pull request by LindsayYoung**
did the sql need to adjust the API output

### CODE REVIEW

**Comment by LindsayYoung** [comment]
This replaces the totals/entity-receipts and totals/entity-disbursements with totals/by_entity 

the results are now:
```
    {
      "cumulative_pac_disbursements": 4394745.97,
      "cumulative_party_receipts": 25547921.32,
      "date": "2015-01-31T00:00:00",
      "cumulative_candidate_receipts": 6113.69,
      "cumulative_pac_receipts": 37003697.17,
      "cumulative_canidate_disbursements": 155600.12,
      "cumulative_party_disbursements": 22989711.53,
      "cycle": 2016
    },
    {
      "cumulative_pac_disbursements": 9069295.69,
      "cumulative_party_receipts": 50652289.8,
      "date": "2015-02-28T00:00:00",
      "cumulative_candidate_receipts": 502217.86,
      "cumulative_pac_receipts": 74455998.12,
      "cumulative_canidate_disbursements": 673071.14,
      "cumulative_party_disbursements": 45309841.27,
      "cycle": 2016
    },
```

This will need some front end adjustments. I was talking to Noah, but @xtine does this look reasonable to you?

**Comment by xtine** [comment]
@LindsayYoung: this looks reasonable, and I can just wrangle the data objects for the line charts in one API request instead of two separate requests.

**Comment by noahmanger** [comment]
Working on the front-end now and caught a typo: you have `cumulative_canidate_disbursements` (no `d` after `can`).

**Comment by noahmanger** [comment]
Also, I'm seeing small discrepancies between this data and the data on prod right now:

| | New  | Production   |
|---|---|---|
|  Candidate raised | 2,410,096,764   | 2,267,066,579 |
| PAC raised | 3,144,570,863  | 3,094,562,515 |
| Candidate spent | 2,474,599,553 | 2,239,861,409 |
| PAC spent | 1,537,566,181 | 1,497,352,380 |

**Comment by LindsayYoung** [comment]
This needs to be coordinated with the front end change

**Pull request closed without merging**
