### PR TITLE
Creating indexes for coverage dates on fact* tables; cleaning up obsolete Blaze references

### PR DESCRIPTION
**Pull request by catherinedevlin**

### CODE REVIEW

**Comment by arowla** [comment]
Looks good. Can we add to this PR a comment at the top of each file summarizing where and when it should be run? Like "this runs on box X to do Y before Z can happen," or something like that.

**Comment by rjmajma** [comment]
Hey @catherinedevlin, just checking status on @arowla's comment above.

**Comment by catherinedevlin** [comment]
Did these for the files in data/synch, but not yet for those in data/ddl...

**Comment by arowla** [comment]
Ok, just going ahead with the merge.

**Pull request merged**
