### PR TITLE
[WIP] Add itemized communication costs.

### PR DESCRIPTION
**Pull request by jmcarp**
* [x] Add itemized communication costs
* [x] Add itemized electioneering costs
* [x] Update tests
* [ ] Update docs

### CODE REVIEW

**Comment by citizencontact** [comment]
Not sure if this should be here, but see if itemization's can include any web domains or addresses used. Preferably shown as URLs with http:// even if not linked to. This would allow for associating official web sites with the appropriate campaign committee if the committee includes it in their itemization. This can than be used by external folks to authenticate campaign websites. This may include hosting at social media or other sites like YouTube (e.g. https://www.youtube.com/use/[cmtechannel] or https://www.facebook.com/[cmtepage])

**Comment by jmcarp** [comment]
@citizencontact the itemized records come from Form 7 and Form 9, neither of which seems to include URLs:

http://www.fec.gov/pdf/forms/fecform7.pdf
http://www.fec.gov/pdf/forms/fecfrm9.pdf

I'm not sure where else we'd find URLs--suggestions welcome!

**Comment by jmcarp** [comment]
Ready for review @LindsayYoung. I added some basic documentation, taken directly from the FEC site, but feel free to further update the docs, update filter fields, etc.

**Comment by LindsayYoung** [comment]
@paulclark2 I am looking at our tables and I am concerned that we are missing transactions. Are there other tables that have this info too?

For example, looking at the current site, there are 154 communication cost results for the California Teacher's Union- C70001227.

On the dev server I only see 2 records:
```

fec=> select * from form_76 where org_id='C70001227';

 form_76_sk │ form_tp │  org_id   │ communication_tp │ communication_tp_desc │ communication_class │ communication_dt │ s_o_ind │ s_o_cand_id │  s_o_cand_nm  │ s_o_cand_m_nm │ s_o_cand_prefix │ s_o_cand_f_nm │ s_o_cand_l_nm │ s_o_cand_suffix │ s_o_cand_office │ s_o_cand_office_st │ s_o_cand_office_district │ s_o_rpt_pgi │ communication_cost │ amndt_ind │    tran_id     │ receipt_dt │ election_other_desc │ transaction_tp │  image_num  │ orig_sub_id │ file_num │       sub_id        │       link_id       │ transaction_id │ filing_type │      load_date      │ update_date │         pg_date         
────────────┼─────────┼───────────┼──────────────────┼───────────────────────┼─────────────────────┼──────────────────┼─────────┼─────────────┼───────────────┼───────────────┼─────────────────┼───────────────┼───────────────┼─────────────────┼─────────────────┼────────────────────┼──────────────────────────┼─────────────┼────────────────────┼───────────┼────────────────┼────────────┼─────────────────────┼────────────────┼─────────────┼─────────────┼──────────┼─────────────────────┼─────────────────────┼────────────────┼─────────────┼─────────────────────┼─────────────┼─────────────────────────
    4331923 │ F76A    │ C70001227 │ DM               │                       │ M                   │ 2014-10-20       │ S       │             │ BERA, AMI     │               │                 │ AMI           │ BERA          │                 │                 │ CA                 │ 7                        │ G           │            7120.12 │ A         │ F7603201543571 │            │                     │ 24F            │ 15031374357 │           0 │   999113 │ 2032320151240927664 │ 1012220150016583270 │        3397161 │ P           │ 2015-06-24 18:59:17 │             │ 2015-07-22 22:17:42.986
    4331924 │ F76A    │ C70001227 │ DM               │                       │ M                   │ 2014-10-20       │ S       │             │ AGUILAR, PETE │               │                 │ PETE          │ AGUILAR       │                 │                 │ CA                 │ 31                       │ G           │            7466.72 │ A         │ F7603201543572 │            │                     │ 24F            │ 15031374357 │           0 │   999113 │ 2032320151240927665 │ 1012220150016583270 │        3397161 │ P           │ 2015-06-24 18:59:17 │             │ 2015-07-22 22:17:43.003
(2 rows)

 ```

**Comment by LindsayYoung** [comment]
@citizencontact the urls for committee's websites are on the Form 1, you can find that info for a committee in the [committee detail view](https://api.open.fec.gov/developers/#!/committee/get_committee_committee_id) of a committee, the field is called `website`

**Comment by PaulClark2** [comment]
@LindsayYoung I think you'll get better results using `f_item_receipt_or_exp`

`select * from f_item_receipt_or_exp where rpt_yr in (2013, 2014) and cmte_id = 'C70001227';`

**Comment by jmcarp** [comment]
Closing in favor of #1444.

**Pull request closed without merging**
