### PR TITLE
Use pre-computed election ranges to round up to next election.

### PR DESCRIPTION
**Pull request by jmcarp**
* Use pre-computed election ranges for `election_full` flag
* Limit election ranges to maximum office duration

[Resolves https://github.com/18F/openFEC-web-app/issues/1107]

### CODE REVIEW

**Comment by LindsayYoung** [comment]
This fixes  18F/openFEC-web-app#1107 but introduces an error on the other end of the spectrum. 

If you want to see the full cycle for an election in the future, it doesn't show summary results:
http://localhost:3000/candidate/S2KY00012/?cycle=2020&election_full=true

**Comment by LindsayYoung** [comment]
OK, it is not isolated, other candidates in 2020 also not going on full cycle:
http://localhost:3000/candidate/S2TN00058/?cycle=2020&election_full=true

Candidates running on 2018 have the full cycle same problem:
http://localhost:3000/candidate/S2MO00429/?cycle=2018&election_full=true

**Comment by jmcarp** [comment]
Good catch. Those issues don't appear related to this patch, though--looks like they originate from #1473. I'll push a fix here in a few minutes.

**Comment by LindsayYoung** [comment]
Looking back at the test cases but I am going to try again because I think my last migration might have been clobbered. 

Bugs from #1473:
http://localhost:3000/candidate/S2KY00012/?cycle=2020&election_full=true
http://localhost:3000/candidate/S2KY00012/?cycle=1982&election_full=true  -error
http://localhost:3000/candidate/S2MO00429/?cycle=2018&election_full=true
Reported bug #1107:
http://localhost:3000/candidate/S2KY00012/?cycle=1982&election_full=true  -error

**Comment by LindsayYoung** [comment]
Woo Hoo! they are all working. I will poke around a but and merge if it all looks okay!

**Pull request merged**
