### PR TITLE
Changed the PR procedure to include usage of '[WIP]' in the title.

### PR DESCRIPTION
**Pull request by arowla**
Suggested change. The nice thing about this is that it makes the work-in-progress-ness explicit, as opposed to the more implicit assigned/unassigned convention. What do you all think?

### CODE REVIEW

**Comment by rjmajma** [comment]
+1

**Comment by arowla** [comment]
Dang you're fast @rjmajma :rocket:

**Comment by LindsayYoung** [comment]
fine with me

**Comment by rjmajma** [comment]
Lindsay is so ahead of the curve that she already does this.

**Comment by LindsayYoung** [comment]
I have connections who look out for me ;)

**Pull request merged**
