### PR TITLE
Configuring New Relic

### PR DESCRIPTION
**Pull request by LindsayYoung**
The instructions seem very straight forward but I have not gotten it working yet.

### CODE REVIEW

**Comment by LindsayYoung** [comment]
I think we should check back on this when we have https going and we are finished with the production environment. But, I got it working in the test environment so I am considering #555 done.

**Comment by arowla** [comment]
@LindsayYoung anything that should be done before or after we merge this one?

**Comment by LindsayYoung** [comment]
I think it is good to go, it worked on testing so it should work in production. Do you want me to deal with the merge conflict?

**Comment by arowla** [comment]
That would be helpful!

On Wed, Apr 22, 2015 at 4:35 PM, Lindsay Young <notifications@github.com>
wrote:

> I think it is good to go, it worked on testing so it should work in
> production. Do you want me to deal with the merge conflict?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/openFEC/pull/570#issuecomment-95327373>.
>



-- 
Alison Rowland
Technical Lead, https://fbopen.gsa.gov | 18F
202-317-0124

**Comment by LindsayYoung** [comment]
merge conflict resolved

**Pull request merged**
