### PR TITLE
[WIP] Manage schema updates with airflow.

### LINKED ISSUE #1515: Explicitly track dependencies between data views
Some of our data views are built directly from the raw FEC tables, but others depend on a chain of our own views. For example, the candidate full-text search view (ofec_candidate_fulltext_mv) depends on the candidate detail view (ofec_candidate_detail_mv). If the views are created in the wrong order, the process will crash. If the views are updated in the wrong order, some views may be stale.

At the moment, we're using the very brittle approach of running sql files in alphabetical order by file name. Instead, I propose that we explicitly declare dependencies between data import and refresh steps and ensure that all steps run in an appropriate order. Airbnb's airflow library is designed to solve exactly this kind of problem and might be a good candidate--or if that's overkill, we can build a directed graph of view dependencies and run steps in topologically sorted order.

### PR DESCRIPTION
**Pull request by jmcarp**
Instead of running schema updates in order by filename, explicitly declare dependencies between tasks and manage updates using airflow. This patch is a work in progress but includes enough work to give a sense of the approach--I'd like to discuss with @LindsayYoung and @ccostino, and anybody else who's interested, and decide how to proceed.

[Resolves #1515]

I thought I'd include a few screenshots of the airflow interface. I find it really useful to be able to see the dependencies between data loading tasks visually, and it's also helpful to be able to track the progress of the various update tasks in real time:

screen shot 2016-02-15 at 11 36 02 pm
screen shot 2016-02-15 at 11 36 18 pm

### CODE REVIEW

**Comment by LindsayYoung** [comment]
Can we schedule a time to talk about this one?

**Comment by jmcarp** [comment]
Sounds good! Want to pick a time when we're all free? While we're at it, we also need to talk over #1502 and #1517, the latter of which should include @noahmanger.

**Comment by noahmanger** [comment]
Great. Yeah I'd love to be in these convos.

**Comment by LindsayYoung** [comment]
@noahmanger I will send you an invite

**Comment by noahmanger** [comment]
Do we still want to review this patch this sprint? Or should we move it to the backlog?

**Comment by ccostino** [comment]
@noahmanger:  Actually if it'd be possible to do so, I think it'd be a good thing.  Not only does this patch provide a means of executing scripts in the correct order and managing them, it also drops the materialized views so we're dealing with just the tables directly.  This should theoretically simplify things from a data management standpoint.

@jmcarp, do you agree, or do you feel this should come at a later point when we can devote more time to it directly?

**Pull request closed without merging**
